# Generated by Django 5.0.6 on 2024-06-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cod', models.CharField(max_length=10)),
                ('img_url', models.CharField(max_length=200)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='collection.set')),
            ],
        ),
    ]
