# Generated by Django 5.0.6 on 2024-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_card_set_alter_set_game_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='collection.card'),
        ),
    ]
