# Generated by Django 5.0.6 on 2024-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_transaction_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
