# Generated by Django 5.0.6 on 2024-06-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_listing_created_at_transaction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
