# Generated by Django 5.0.6 on 2024-06-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_listing_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
