# Generated by Django 5.0.6 on 2024-06-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_paypal_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paypal_url',
        ),
    ]
